# coding: utf-8

"""
    KomMonitor Data Access API

    erster Entwurf einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.georesource_put_input_type import GeoresourcePUTInputType

class TestGeoresourcePUTInputType(unittest.TestCase):
    """GeoresourcePUTInputType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeoresourcePUTInputType:
        """Test GeoresourcePUTInputType
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeoresourcePUTInputType`
        """
        model = GeoresourcePUTInputType()
        if include_optional:
            return GeoresourcePUTInputType(
                geo_json_string = '',
                period_of_validity = openapi_client.models.period_of_validity_type.PeriodOfValidityType(
                    end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
                is_partial_update = True
            )
        else:
            return GeoresourcePUTInputType(
                geo_json_string = '',
                period_of_validity = openapi_client.models.period_of_validity_type.PeriodOfValidityType(
                    end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
                is_partial_update = True,
        )
        """

    def testGeoresourcePUTInputType(self):
        """Test GeoresourcePUTInputType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
