# coding: utf-8

"""
    KomMonitor Data Access API

    erster Entwurf einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.roles_controller_api import RolesControllerApi


class TestRolesControllerApi(unittest.TestCase):
    """RolesControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RolesControllerApi()

    def tearDown(self) -> None:
        pass

    def test_add_role(self) -> None:
        """Test case for add_role

        Register a new role
        """
        pass

    def test_delete_role(self) -> None:
        """Test case for delete_role

        Delete the role
        """
        pass

    def test_get_role_by_id(self) -> None:
        """Test case for get_role_by_id

        retrieve information about the selected role
        """
        pass

    def test_get_roles(self) -> None:
        """Test case for get_roles

        retrieve information about available roles
        """
        pass

    def test_update_role(self) -> None:
        """Test case for update_role

        Modify role information
        """
        pass


if __name__ == '__main__':
    unittest.main()
