# coding: utf-8

"""
    KomMonitor Data Access API

    erster Entwurf einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.indicator_post_input_type_refrences_to_other_indicators import IndicatorPOSTInputTypeRefrencesToOtherIndicators

class TestIndicatorPOSTInputTypeRefrencesToOtherIndicators(unittest.TestCase):
    """IndicatorPOSTInputTypeRefrencesToOtherIndicators unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IndicatorPOSTInputTypeRefrencesToOtherIndicators:
        """Test IndicatorPOSTInputTypeRefrencesToOtherIndicators
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IndicatorPOSTInputTypeRefrencesToOtherIndicators`
        """
        model = IndicatorPOSTInputTypeRefrencesToOtherIndicators()
        if include_optional:
            return IndicatorPOSTInputTypeRefrencesToOtherIndicators(
                indicator_id = '',
                reference_description = ''
            )
        else:
            return IndicatorPOSTInputTypeRefrencesToOtherIndicators(
        )
        """

    def testIndicatorPOSTInputTypeRefrencesToOtherIndicators(self):
        """Test IndicatorPOSTInputTypeRefrencesToOtherIndicators"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
