# coding: utf-8

"""
    KomMonitor Data Access API

    erster Entwurf einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.process_input_type import ProcessInputType

class TestProcessInputType(unittest.TestCase):
    """ProcessInputType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessInputType:
        """Test ProcessInputType
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessInputType`
        """
        model = ProcessInputType()
        if include_optional:
            return ProcessInputType(
                data_type = 'string',
                default_value = '',
                description = '',
                max_parameter_value_for_numeric_inputs = 1.337,
                min_parameter_value_for_numeric_inputs = 1.337,
                name = ''
            )
        else:
            return ProcessInputType(
                data_type = 'string',
                default_value = '',
                description = '',
                name = '',
        )
        """

    def testProcessInputType(self):
        """Test ProcessInputType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
