# coding: utf-8

"""
    KomMonitor Data Access API

    erster Entwurf einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.process_script_overview_type import ProcessScriptOverviewType

class TestProcessScriptOverviewType(unittest.TestCase):
    """ProcessScriptOverviewType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProcessScriptOverviewType:
        """Test ProcessScriptOverviewType
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProcessScriptOverviewType`
        """
        model = ProcessScriptOverviewType()
        if include_optional:
            return ProcessScriptOverviewType(
                description = '',
                indicator_id = '',
                name = '',
                required_georesource_ids = [
                    ''
                    ],
                required_indicator_ids = [
                    ''
                    ],
                script_id = '',
                script_type = '',
                variable_process_parameters = [
                    openapi_client.models.process_input_type.ProcessInputType(
                        data_type = 'string', 
                        default_value = '', 
                        description = '', 
                        max_parameter_value_for_numeric_inputs = 1.337, 
                        min_parameter_value_for_numeric_inputs = 1.337, 
                        name = '', )
                    ]
            )
        else:
            return ProcessScriptOverviewType(
                description = '',
                indicator_id = '',
                name = '',
                required_georesource_ids = [
                    ''
                    ],
                required_indicator_ids = [
                    ''
                    ],
                script_id = '',
                variable_process_parameters = [
                    openapi_client.models.process_input_type.ProcessInputType(
                        data_type = 'string', 
                        default_value = '', 
                        description = '', 
                        max_parameter_value_for_numeric_inputs = 1.337, 
                        min_parameter_value_for_numeric_inputs = 1.337, 
                        name = '', )
                    ],
        )
        """

    def testProcessScriptOverviewType(self):
        """Test ProcessScriptOverviewType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
