# coding: utf-8

"""
    KomMonitor Data Access API

    erster Entwurf einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.spatial_unit_patch_input_type import SpatialUnitPATCHInputType

class TestSpatialUnitPATCHInputType(unittest.TestCase):
    """SpatialUnitPATCHInputType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpatialUnitPATCHInputType:
        """Test SpatialUnitPATCHInputType
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpatialUnitPATCHInputType`
        """
        model = SpatialUnitPATCHInputType()
        if include_optional:
            return SpatialUnitPATCHInputType(
                allowed_roles = [
                    ''
                    ],
                metadata = openapi_client.models.common_metadata_type.CommonMetadataType(
                    contact = '', 
                    databasis = '', 
                    datasource = '', 
                    description = '', 
                    last_update = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    literature = '', 
                    note = '', 
                    srid_epsg = 1.337, 
                    update_interval = 'ARBITRARY', ),
                next_lower_hierarchy_level = '',
                next_upper_hierarchy_level = ''
            )
        else:
            return SpatialUnitPATCHInputType(
                allowed_roles = [
                    ''
                    ],
                metadata = openapi_client.models.common_metadata_type.CommonMetadataType(
                    contact = '', 
                    databasis = '', 
                    datasource = '', 
                    description = '', 
                    last_update = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    literature = '', 
                    note = '', 
                    srid_epsg = 1.337, 
                    update_interval = 'ARBITRARY', ),
                next_lower_hierarchy_level = '',
                next_upper_hierarchy_level = '',
        )
        """

    def testSpatialUnitPATCHInputType(self):
        """Test SpatialUnitPATCHInputType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
