# coding: utf-8

"""
    KomMonitor Data Access API

    erster Entwurf einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.common_metadata_type import CommonMetadataType

class TestCommonMetadataType(unittest.TestCase):
    """CommonMetadataType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommonMetadataType:
        """Test CommonMetadataType
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommonMetadataType`
        """
        model = CommonMetadataType()
        if include_optional:
            return CommonMetadataType(
                contact = '',
                databasis = '',
                datasource = '',
                description = '',
                last_update = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                literature = '',
                note = '',
                srid_epsg = 1.337,
                update_interval = 'ARBITRARY'
            )
        else:
            return CommonMetadataType(
                contact = '',
                datasource = '',
                description = '',
                srid_epsg = 1.337,
                update_interval = 'ARBITRARY',
        )
        """

    def testCommonMetadataType(self):
        """Test CommonMetadataType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
