# coding: utf-8

"""
    KomMonitor Data Access API

    erster Entwurf einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.topics_public_controller_api import TopicsPublicControllerApi


class TestTopicsPublicControllerApi(unittest.TestCase):
    """TopicsPublicControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TopicsPublicControllerApi()

    def tearDown(self) -> None:
        pass

    def test_get_topic_by_id(self) -> None:
        """Test case for get_topic_by_id

        retrieve information about the selected topic
        """
        pass

    def test_get_topics(self) -> None:
        """Test case for get_topics

        retrieve information about available topics
        """
        pass


if __name__ == '__main__':
    unittest.main()
