# coding: utf-8

"""
    KomMonitor Data Access API

    erster Entwurf einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.topics_controller_api import TopicsControllerApi


class TestTopicsControllerApi(unittest.TestCase):
    """TopicsControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TopicsControllerApi()

    def tearDown(self) -> None:
        pass

    def test_add_topic(self) -> None:
        """Test case for add_topic

        Register a new topic
        """
        pass

    def test_delete_topic(self) -> None:
        """Test case for delete_topic

        Delete the topic
        """
        pass

    def test_update_topic(self) -> None:
        """Test case for update_topic

        Modify topic information
        """
        pass


if __name__ == '__main__':
    unittest.main()
