# coding: utf-8

"""
    KomMonitor Data Access API

    erster Entwurf einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.georecources_controller_api import GeorecourcesControllerApi


class TestGeorecourcesControllerApi(unittest.TestCase):
    """GeorecourcesControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GeorecourcesControllerApi()

    def tearDown(self) -> None:
        pass

    def test_add_georesource_as_body(self) -> None:
        """Test case for add_georesource_as_body

        Add a new geo-resource
        """
        pass

    def test_delete_all_georesource_features_by_id(self) -> None:
        """Test case for delete_all_georesource_features_by_id

        Delete all features/contents of the selected geo-resource dataset
        """
        pass

    def test_delete_georesource_by_id(self) -> None:
        """Test case for delete_georesource_by_id

        Delete the features/contents of the selected geo-resource dataset
        """
        pass

    def test_delete_georesource_by_id_and_year_and_month(self) -> None:
        """Test case for delete_georesource_by_id_and_year_and_month

        Delete the features/contents of the selected geo-resource dataset, selected by year and month
        """
        pass

    def test_get_all_georesource_features_by_id(self) -> None:
        """Test case for get_all_georesource_features_by_id

        retrieve all feature entries for all applicable periods of validity for the selected geo-resource dataset (hence might contain each feature multiple times if they exist for different periods of validity)
        """
        pass

    def test_get_georesource_by_id(self) -> None:
        """Test case for get_georesource_by_id

        retrieve information about available features of the selected geo-resource dataset
        """
        pass

    def test_get_georesource_by_id_and_year_and_month(self) -> None:
        """Test case for get_georesource_by_id_and_year_and_month

        retrieve the features according to the selected geo-resource dataset and selected year and month as GeoJSON
        """
        pass

    def test_get_georesource_schema_by_level(self) -> None:
        """Test case for get_georesource_schema_by_level

        retrieve the JSON schema for the selected geo-resource dataset
        """
        pass

    def test_get_georesources(self) -> None:
        """Test case for get_georesources

        retrieve information about available features of different geo-resource datasets
        """
        pass

    def test_update_georesource_as_body(self) -> None:
        """Test case for update_georesource_as_body

        Modify/Update the features of the selected geo-resource dataset
        """
        pass

    def test_update_georesource_metadata_as_body(self) -> None:
        """Test case for update_georesource_metadata_as_body

        Modify/Update the metadata of the selected geo-resource dataset
        """
        pass


if __name__ == '__main__':
    unittest.main()
