# coding: utf-8

"""
    KomMonitor Data Access API

    erster Entwurf einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.georesource_overview_type import GeoresourceOverviewType

class TestGeoresourceOverviewType(unittest.TestCase):
    """GeoresourceOverviewType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GeoresourceOverviewType:
        """Test GeoresourceOverviewType
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeoresourceOverviewType`
        """
        model = GeoresourceOverviewType()
        if include_optional:
            return GeoresourceOverviewType(
                allowed_roles = [
                    ''
                    ],
                aoi_color = '',
                available_periods_of_validity = [
                    openapi_client.models.period_of_validity_type.PeriodOfValidityType(
                        end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                dataset_name = '',
                georesource_id = '',
                is_aoi = True,
                is_loi = True,
                is_poi = True,
                loi_color = '',
                loi_dash_array_string = '',
                loi_width = 1.337,
                metadata = openapi_client.models.common_metadata_type.CommonMetadataType(
                    contact = '', 
                    databasis = '', 
                    datasource = '', 
                    description = '', 
                    last_update = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    literature = '', 
                    note = '', 
                    srid_epsg = 1.337, 
                    update_interval = 'ARBITRARY', ),
                poi_marker_color = 'white',
                poi_symbol_bootstrap3_name = '',
                poi_symbol_color = 'white',
                topic_reference = '',
                wfs_url = '',
                wms_url = '',
                user_permissions = [
                    ''
                    ]
            )
        else:
            return GeoresourceOverviewType(
                available_periods_of_validity = [
                    openapi_client.models.period_of_validity_type.PeriodOfValidityType(
                        end_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        start_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                dataset_name = '',
                georesource_id = '',
                is_aoi = True,
                is_loi = True,
                is_poi = True,
                metadata = openapi_client.models.common_metadata_type.CommonMetadataType(
                    contact = '', 
                    databasis = '', 
                    datasource = '', 
                    description = '', 
                    last_update = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    literature = '', 
                    note = '', 
                    srid_epsg = 1.337, 
                    update_interval = 'ARBITRARY', ),
                topic_reference = '',
                wfs_url = '',
                wms_url = '',
        )
        """

    def testGeoresourceOverviewType(self):
        """Test GeoresourceOverviewType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
