version: '3'

# networks:
#   kommonitor:
#     name: kommonitor
#     external: true

services:
  kommonitor-processes-api:
   image: kommonitor/processes-api:latest
   environment:
   - KC_HOSTNAME=keycloak.url
   - KC_HOSTNAME_PATH=
   - KC_REALM_NAME=kommonitor
   - KC_CLIENT_ID=kommonitor-processes-api
   - KC_CLIENT_SECRET=********
   - KC_TARGET_CLIENT_ID=kommonitor-data-management
   - KOMMONITOR_DATA_MANAGEMENT_URL=https://management.url/  #without /management at the end; only until entry point of data-management component
   - PROCESS_RESULTS_DIR=https://kommonitor.fbg-hsbo.de/ #i.e. data management entrypoint without /management at the end; 
   - KOMMONITOR_PROCESSES_API_ALLOWED_CORS_ORIGINS=http://localhost:8000 # URL of kommonitor domain
   ports:
     - 8001:8000
     - 8099:8099
     - 4200:4200
     - 8095:8095
  #  networks:
  #    - kommonitor