# coding: utf-8

"""
    KomMonitor Data Access API

    Definition einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AdminRoleType(str, Enum):
    """
    Permissions for administrative tasks regarding resources, themes and users
    """

    """
    allowed enum values
    """
    CLIENT_MINUS_USERS_MINUS_CREATOR = 'client-users-creator'
    UNIT_MINUS_USERS_MINUS_CREATOR = 'unit-users-creator'
    CLIENT_MINUS_RESOURCES_MINUS_CREATOR = 'client-resources-creator'
    UNIT_MINUS_RESOURCES_MINUS_CREATOR = 'unit-resources-creator'
    CLIENT_MINUS_THEMES_MINUS_CREATOR = 'client-themes-creator'
    UNIT_MINUS_THEMES_MINUS_CREATOR = 'unit-themes-creator'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AdminRoleType from a JSON string"""
        return cls(json.loads(json_str))


