# coding: utf-8

"""
    KomMonitor Data Access API

    Definition einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class CreationTypeEnum(str, Enum):
    """
    CreationTypeEnum
    """

    """
    allowed enum values
    """
    INSERTION = 'INSERTION'
    COMPUTATION = 'COMPUTATION'
    AGGREGATION = 'AGGREGATION'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CreationTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


