# coding: utf-8

"""
    KomMonitor Data Access API

    Definition einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Union
from typing_extensions import Annotated
from openapi_client.models.default_classification_mapping_item_type import DefaultClassificationMappingItemType
from typing import Optional, Set
from typing_extensions import Self

class DefaultClassificationMappingType(BaseModel):
    """
    DefaultClassificationMappingType
    """ # noqa: E501
    color_brewer_scheme_name: StrictStr = Field(description="the name of the colorBrewer color scheme used to define the colors for classification (see project http://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3 for colorSchemes). Set to 'INDIVIDUAL' if colors are set arbitrarily.", alias="colorBrewerSchemeName")
    num_classes: Union[Annotated[float, Field(le=9, strict=True, ge=1)], Annotated[int, Field(le=9, strict=True, ge=1)]] = Field(description="the number of classes", alias="numClasses")
    classification_method: StrictStr = Field(description="the classification method as enumeration", alias="classificationMethod")
    items: List[DefaultClassificationMappingItemType] = Field(description="array of classification mapping items. each item holds the break values for a certain spatial unit. not all spatial units of a certain indicator must be set.")
    __properties: ClassVar[List[str]] = ["colorBrewerSchemeName", "numClasses", "classificationMethod", "items"]

    @field_validator('classification_method')
    def classification_method_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['REGIONAL_DEFAULT', 'JENKS', 'EQUAL_INTERVAL', 'QUANTILE']):
            raise ValueError("must be one of enum values ('REGIONAL_DEFAULT', 'JENKS', 'EQUAL_INTERVAL', 'QUANTILE')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DefaultClassificationMappingType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DefaultClassificationMappingType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "colorBrewerSchemeName": obj.get("colorBrewerSchemeName"),
            "numClasses": obj.get("numClasses"),
            "classificationMethod": obj.get("classificationMethod"),
            "items": [DefaultClassificationMappingItemType.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None
        })
        return _obj


