# coding: utf-8

"""
    KomMonitor Data Access API

    Definition einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from openapi_client.models.color_type import ColorType
from openapi_client.models.common_metadata_type import CommonMetadataType
from openapi_client.models.period_of_validity_type import PeriodOfValidityType
from openapi_client.models.permission_level_type import PermissionLevelType
from openapi_client.models.poi_marker_style_enum import PoiMarkerStyleEnum
from typing import Optional, Set
from typing_extensions import Self

class GeoresourceOverviewType(BaseModel):
    """
    GeoresourceOverviewType
    """ # noqa: E501
    permissions: Optional[List[StrictStr]] = Field(default=None, description="list of permissions on this entity")
    aoi_color: Optional[StrictStr] = Field(default=None, description="color name or color code (i.e. hex number) for areas of interest", alias="aoiColor")
    available_periods_of_validity: List[PeriodOfValidityType] = Field(alias="availablePeriodsOfValidity")
    dataset_name: StrictStr = Field(description="the meaningful name of the dataset", alias="datasetName")
    georesource_id: StrictStr = Field(description="the unique identifier of the dataset", alias="georesourceId")
    is_aoi: StrictBool = Field(description="boolean value indicating if the dataset contains areas of interest", alias="isAOI")
    is_loi: StrictBool = Field(description="boolean value indicating if the dataset contains lines of interest", alias="isLOI")
    is_poi: StrictBool = Field(description="boolean value indicating if the dataset contains points of interest", alias="isPOI")
    is_public: StrictBool = Field(description="flag whether the resource is publicly accessible", alias="isPublic")
    loi_color: Optional[StrictStr] = Field(default=None, description="color name or color code (i.e. hex number) for lines of interest", alias="loiColor")
    loi_dash_array_string: Optional[StrictStr] = Field(default=None, description="sring of line stroke dash array for lines of interest (e.g. 20,20; see https://developer.mozilla.org/de/docs/Web/SVG/Attribute/stroke-dasharray)", alias="loiDashArrayString")
    loi_width: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="display width for lines of interest (number of pixels in leaflet)", alias="loiWidth")
    metadata: CommonMetadataType
    owner_id: StrictStr = Field(description="identifier of the owning group", alias="ownerId")
    poi_marker_style: Optional[PoiMarkerStyleEnum] = Field(default=None, alias="poiMarkerStyle")
    poi_marker_text: Optional[Annotated[str, Field(strict=True, max_length=3)]] = Field(default=None, description="the poi marker text string to be used if poiMarkerStyle is set to text", alias="poiMarkerText")
    poi_marker_color: Optional[ColorType] = Field(default=None, alias="poiMarkerColor")
    poi_symbol_bootstrap3_name: Optional[StrictStr] = Field(default=None, description="If georesource is a POI then custom POI marker symbol can be set by specifying the name of a Bootstrap 3 glyphicon symbol (i.e. \"home\" for a home symbol or \"education\" for a students hat symbol)", alias="poiSymbolBootstrap3Name")
    poi_symbol_color: Optional[ColorType] = Field(default=None, alias="poiSymbolColor")
    topic_reference: StrictStr = Field(description="id of the last topic hierarchy entity ", alias="topicReference")
    user_permissions: Optional[List[PermissionLevelType]] = Field(default=None, description="list of permissions that are effective on this dataset for the current user ", alias="userPermissions")
    wfs_url: Optional[StrictStr] = Field(default=None, description="the URL of a running WFS instance serving the spatial features of the associated dataset", alias="wfsUrl")
    wms_url: Optional[StrictStr] = Field(default=None, description="the URL of a running WMS instance serving the spatial features of the associated dataset", alias="wmsUrl")
    __properties: ClassVar[List[str]] = ["permissions", "aoiColor", "availablePeriodsOfValidity", "datasetName", "georesourceId", "isAOI", "isLOI", "isPOI", "isPublic", "loiColor", "loiDashArrayString", "loiWidth", "metadata", "ownerId", "poiMarkerStyle", "poiMarkerText", "poiMarkerColor", "poiSymbolBootstrap3Name", "poiSymbolColor", "topicReference", "userPermissions", "wfsUrl", "wmsUrl"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GeoresourceOverviewType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in available_periods_of_validity (list)
        _items = []
        if self.available_periods_of_validity:
            for _item_available_periods_of_validity in self.available_periods_of_validity:
                if _item_available_periods_of_validity:
                    _items.append(_item_available_periods_of_validity.to_dict())
            _dict['availablePeriodsOfValidity'] = _items
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GeoresourceOverviewType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "permissions": obj.get("permissions"),
            "aoiColor": obj.get("aoiColor"),
            "availablePeriodsOfValidity": [PeriodOfValidityType.from_dict(_item) for _item in obj["availablePeriodsOfValidity"]] if obj.get("availablePeriodsOfValidity") is not None else None,
            "datasetName": obj.get("datasetName"),
            "georesourceId": obj.get("georesourceId"),
            "isAOI": obj.get("isAOI"),
            "isLOI": obj.get("isLOI"),
            "isPOI": obj.get("isPOI"),
            "isPublic": obj.get("isPublic"),
            "loiColor": obj.get("loiColor"),
            "loiDashArrayString": obj.get("loiDashArrayString"),
            "loiWidth": obj.get("loiWidth"),
            "metadata": CommonMetadataType.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None,
            "ownerId": obj.get("ownerId"),
            "poiMarkerStyle": obj.get("poiMarkerStyle"),
            "poiMarkerText": obj.get("poiMarkerText"),
            "poiMarkerColor": obj.get("poiMarkerColor"),
            "poiSymbolBootstrap3Name": obj.get("poiSymbolBootstrap3Name"),
            "poiSymbolColor": obj.get("poiSymbolColor"),
            "topicReference": obj.get("topicReference"),
            "userPermissions": obj.get("userPermissions"),
            "wfsUrl": obj.get("wfsUrl"),
            "wmsUrl": obj.get("wmsUrl")
        })
        return _obj


