# coding: utf-8

"""
    KomMonitor Data Access API

    erster Entwurf einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List
from pydantic import BaseModel, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class GeoresourceReferenceType(BaseModel):
    """
    a reference to georesource, e.g. a resource that is used to compute the main indicator
    """ # noqa: E501
    referenced_georesource_description: StrictStr = Field(description="a meaningful description of how the referenced georesource is related to the main indicator", alias="referencedGeoresourceDescription")
    referenced_georesource_id: StrictStr = Field(description="unique identifier of the referenced georesource", alias="referencedGeoresourceId")
    referenced_georesource_name: StrictStr = Field(description="the meaningful name of the referenced georesource", alias="referencedGeoresourceName")
    __properties: ClassVar[List[str]] = ["referencedGeoresourceDescription", "referencedGeoresourceId", "referencedGeoresourceName"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GeoresourceReferenceType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of GeoresourceReferenceType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "referencedGeoresourceDescription": obj.get("referencedGeoresourceDescription"),
            "referencedGeoresourceId": obj.get("referencedGeoresourceId"),
            "referencedGeoresourceName": obj.get("referencedGeoresourceName")
        })
        return _obj


