# coding: utf-8

"""
    KomMonitor Data Access API

    erster Entwurf einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictStr
from pydantic import Field
from openapi_client.models.default_classification_mapping_type import DefaultClassificationMappingType
from openapi_client.models.indicator_put_input_type_indicator_values import IndicatorPUTInputTypeIndicatorValues
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class IndicatorPUTInputType(BaseModel):
    """
    IndicatorPUTInputType
    """ # noqa: E501
    allowed_roles: List[StrictStr] = Field(description="list of role identifiers that have read access rights for this dataset", alias="allowedRoles")
    applicable_spatial_unit: StrictStr = Field(alias="applicableSpatialUnit")
    default_classification_mapping: Optional[DefaultClassificationMappingType] = Field(default=None, alias="defaultClassificationMapping")
    indicator_values: List[IndicatorPUTInputTypeIndicatorValues] = Field(description="an array of entries containing indicator values and mapping to spatial features via identifiers", alias="indicatorValues")
    __properties: ClassVar[List[str]] = ["allowedRoles", "applicableSpatialUnit", "defaultClassificationMapping", "indicatorValues"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IndicatorPUTInputType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of default_classification_mapping
        if self.default_classification_mapping:
            _dict['defaultClassificationMapping'] = self.default_classification_mapping.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in indicator_values (list)
        _items = []
        if self.indicator_values:
            for _item in self.indicator_values:
                if _item:
                    _items.append(_item.to_dict())
            _dict['indicatorValues'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of IndicatorPUTInputType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowedRoles": obj.get("allowedRoles"),
            "applicableSpatialUnit": obj.get("applicableSpatialUnit"),
            "defaultClassificationMapping": DefaultClassificationMappingType.from_dict(obj.get("defaultClassificationMapping")) if obj.get("defaultClassificationMapping") is not None else None,
            "indicatorValues": [IndicatorPUTInputTypeIndicatorValues.from_dict(_item) for _item in obj.get("indicatorValues")] if obj.get("indicatorValues") is not None else None
        })
        return _obj


