# coding: utf-8

"""
    KomMonitor Data Access API

    Definition einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class IndicatorTypeEnum(str, Enum):
    """
    indicates whether the indicator is a status indicator (values represent the extent of the watched phenomenon for a certain point in time) or a dynamic indicator (values represent the change of extent of the watched phenomenon within a certain period of time)
    """

    """
    allowed enum values
    """
    STATUS_ABSOLUTE = 'STATUS_ABSOLUTE'
    DYNAMIC_ABSOLUTE = 'DYNAMIC_ABSOLUTE'
    STATUS_RELATIVE = 'STATUS_RELATIVE'
    DYNAMIC_RELATIVE = 'DYNAMIC_RELATIVE'
    STATUS_STANDARDIZED = 'STATUS_STANDARDIZED'
    DYNAMIC_STANDARDIZED = 'DYNAMIC_STANDARDIZED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IndicatorTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


