# coding: utf-8

"""
    KomMonitor Data Access API

    Definition einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class IndicatorPropertiesWithoutGeomType(BaseModel):
    """
    IndicatorPropertiesWithoutGeomType
    """ # noqa: E501
    ID: StrictStr = Field(description="the id of the spatial feature", alias="ID")
    NAME: StrictStr = Field(description="the name of the spatial feature", alias="NAME")
    valid_start_date: StrictStr = Field(description="the start date from which on the spatial feature is valid", alias="validStartDate")
    valid_end_date: Optional[StrictStr] = Field(default=None, description="the end date until the spatial feature is valid - or null if not set", alias="validEndDate")
    __properties: ClassVar[List[str]] = ["id", "name", "validStartDate", "validEndDate"]

    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __getitem__(self, item: str) -> Any:
        try:
            return getattr(self, item)
        except AttributeError:
            raise KeyError(item)

    def __setitem__(self, key, value):
        setattr(self, key, value)


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IndicatorPropertiesWithoutGeomType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IndicatorPropertiesWithoutGeomType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        data = {
            "ID": obj.get("ID"),
            "NAME": obj.get("NAME"),
            "valid_start_date": obj.get("validStartDate"),
            "valid_end_date": obj.get("validEndDate")
        }

        known_keys = {"ID", "NAME", "validStartDate", "validEndDate"}

        # 3. Add all other keys from the source object that weren't mapped
        for key, value in obj.items():
            if key not in known_keys:
                data[key] = value

        _obj = cls.model_validate(data)

        return _obj


