# coding: utf-8

"""
    KomMonitor Data Access API

    erster Entwurf einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr, field_validator
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ProcessInputType(BaseModel):
    """
    ProcessInputType
    """ # noqa: E501
    data_type: StrictStr = Field(description="the data type of the process input", alias="dataType")
    default_value: StrictStr = Field(description="the default value of the process parameter", alias="defaultValue")
    description: StrictStr = Field(description="a short description of the process input")
    max_parameter_value_for_numeric_inputs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="the maximum value that is allowed for the process parameter", alias="maxParameterValueForNumericInputs")
    min_parameter_value_for_numeric_inputs: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="the minimum value that is allowed for the process parameter", alias="minParameterValueForNumericInputs")
    name: StrictStr = Field(description="the name of the process input parameter")
    __properties: ClassVar[List[str]] = ["dataType", "defaultValue", "description", "maxParameterValueForNumericInputs", "minParameterValueForNumericInputs", "name"]

    @field_validator('data_type')
    def data_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('string', 'boolean', 'integer', 'double'):
            raise ValueError("must be one of enum values ('string', 'boolean', 'integer', 'double')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ProcessInputType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ProcessInputType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dataType": obj.get("dataType"),
            "defaultValue": obj.get("defaultValue"),
            "description": obj.get("description"),
            "maxParameterValueForNumericInputs": obj.get("maxParameterValueForNumericInputs"),
            "minParameterValueForNumericInputs": obj.get("minParameterValueForNumericInputs"),
            "name": obj.get("name")
        })
        return _obj


