# coding: utf-8

"""
    KomMonitor Data Access API

    Definition einer Datenzugriffs-API, die den Zugriff auf die KomMonitor-Datenhaltungsschicht kapselt.

    The version of the OpenAPI document: 0.0.1
    Contact: christian.danowski-buhren@hs-bochum.de
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.topic_resource_enum import TopicResourceEnum
from openapi_client.models.topic_type_enum import TopicTypeEnum
from typing import Optional, Set
from typing_extensions import Self

class TopicOverviewType(BaseModel):
    """
    TopicOverviewType
    """ # noqa: E501
    sub_topics: Optional[List[TopicOverviewType]] = Field(default=None, description="optional list of subTopics", alias="subTopics")
    topic_description: StrictStr = Field(description="short description of the topic", alias="topicDescription")
    topic_id: StrictStr = Field(description="the identifier of the topic", alias="topicId")
    topic_name: StrictStr = Field(description="the topic name", alias="topicName")
    topic_resource: Optional[TopicResourceEnum] = Field(default=None, alias="topicResource")
    topic_type: TopicTypeEnum = Field(alias="topicType")
    display_order: StrictInt = Field(description="an order number to control display order in clients", alias="displayOrder")
    __properties: ClassVar[List[str]] = ["subTopics", "topicDescription", "topicId", "topicName", "topicResource", "topicType", "displayOrder"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TopicOverviewType from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sub_topics (list)
        _items = []
        if self.sub_topics:
            for _item_sub_topics in self.sub_topics:
                if _item_sub_topics:
                    _items.append(_item_sub_topics.to_dict())
            _dict['subTopics'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TopicOverviewType from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "subTopics": [TopicOverviewType.from_dict(_item) for _item in obj["subTopics"]] if obj.get("subTopics") is not None else None,
            "topicDescription": obj.get("topicDescription"),
            "topicId": obj.get("topicId"),
            "topicName": obj.get("topicName"),
            "topicResource": obj.get("topicResource"),
            "topicType": obj.get("topicType"),
            "displayOrder": obj.get("displayOrder")
        })
        return _obj

# TODO: Rewrite to not use raise_errors
TopicOverviewType.model_rebuild(raise_errors=False)

